name: Check

on:
  workflow_call:
  push:
    paths-ignore:
      - "../../README.md"
      - "../../LICENSE"
      - "../../.gitignore"
  pull_request:
    paths-ignore:
      - "../../README.md"
      - "../../LICENSE"
      - "../../.gitignore"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup VITE+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Lint and Type check code
        run: vp check
